### ISSUE TITLE
Debian Install Script error

### ISSUE THREAD

**Issue by d4t4king** [leviathan-framework/leviathan#6]
```
/usr/bin/strip /usr/local/bin/ncrack
/usr/bin/install -c -c -m 644 docs/ncrack.1 /usr/local/share/man/man1/
/usr/bin/install -c -c -m 644 ncrack-services /usr/local/share/ncrack/
/usr/bin/install -c -c -m 644 lists/* /usr/local/share/ncrack/
NCRACK SUCCESSFULLY INSTALLED
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

This on Debian Jessie (8.7).

**Comment by utkusen** [comment]
can you try this solution?: http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread
